"""Create a baseline migrations

Revision ID: 61f4001f95f9
Revises: b02c166bce2b
Create Date: 2025-04-20 13:45:00.396272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f4001f95f9'
down_revision: Union[str, None] = 'b02c166bce2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_order_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_order_id_fkey', 'orders', 'orderitems', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
