"""Create a baseline migrations

Revision ID: 9cca6c1f9728
Revises: c6dec2299411
Create Date: 2025-04-20 10:08:02.320685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cca6c1f9728'
down_revision: Union[str, None] = 'c6dec2299411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('delivery', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderitems', 'delivery')
    # ### end Alembic commands ###
