"""Create a baseline migrations

Revision ID: a08a5042efb6
Revises: 742a9e4a8037
Create Date: 2025-04-20 11:13:20.048198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a08a5042efb6'
down_revision: Union[str, None] = '742a9e4a8037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresss',
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', NOW())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', NOW())"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('accepted', 'delivery', 'delivered', name='status'),
               nullable=False,
               existing_server_default=sa.text("accepted'::status"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('accepted', 'delivery', 'delivered', name='status'),
               nullable=True,
               existing_server_default=sa.text("accepted'::status"))
    op.drop_table('addresss')
    # ### end Alembic commands ###
